[project]
name = "tuition-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "Flask_SocketIO>=5.4.1",
    "python-dotenv>=1.2.2",
    "flask-pymongo>=3.0.1",
    "ipykernel>=7.3.0",
    "gevent>=26.8.0",
    "gevent-websocket>=0.10.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
